mtps-run-tests
SRPM packages cannot be dnf-installed and the test
would later fail on them.
Note: if the repository is prepared by mini-tps, then there
should be no SRPMs inside. However, the repository can be prepared
by CI systems and SRPMs may appear there.
=> Exclude SRPM if they happen to be in the test repository

mtps-get-task
Guessing the volume name is not reliable and things can break
unexpectedly in future.
This happened recently in Fedora [1].
Luckily for us, Koji maintains symlinks on the default volume
for builds on other volumes [2]. This means that we should be able
to just ignore the volume in the URL completely.
For example:
${BREWWEB_ROOT}/vol/rhel-9/packages/systemd/250/10.el9/x86_64/systemd-250-10.el9.x86_64.rpm
We can use just:
${BREWWEB_ROOT}/packages/systemd/250/10.el9/x86_64/systemd-250-10.el9.x86_64.rpm
[1]: https://pagure.io/fedora-ci/general/issue/356
[2]: https://github.com/koji-project/koji/blob/master/docs/source/volumes.rst#symlinks-on-default-volume
=> Ignore volumes when constructing Koji URLs

.github/dependabot.yml, .github/workflows/differential-shellcheck.yml
Looking at this repository, I think it might be beneficial to have a shell linter.
Differential ShellCheck is a GitHub action that performs differential ShellCheck scans on shell scripts changed via PR and reports results directly in PR. The beauty of differential scans is that you will get reports only about newly added defects. Differential ShellCheck is able to produce reports in SARIF format. GitHub understands this format and is able to display it nicely as a PR comment, and on the `Files Changed` tab, please see below.
Documentation is available at [@redhat-plumbers-in-action/differential-shellcheck](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme).
> **Note**: _I have also added Dependabot to keep your future workflows up to date_
=> ci: Add Shell linter and Dependabot

mini-tps.spec, mtps-get-task
The --onlyinrepo option wasn't working as expected.
The rest of the script expects to find the list of RPMs
in the "rpms_from_task_all" variable (and its "noarch"
counterpart). "rpms_from_task" is not used for anything later
in the script.
=> Fix --onlyinrepo option in mtps-get-task

mtps-pkg-test
We have to check again if the pakage can be removed after we installed its latest version. It can happen that the update introduced new /etc/dnf/protected.d/* file which makes it uninstallable.
Signed-off-by: Jan Kaluza <jkaluza@redhat.com>
=> OSCI-4333: Do not try removing package which introduced /etc/dnf/protected.d file.

mini-tps.spec, mtps-pkg-test, mtps-run-tests
YUM operations can succeed, but there can be scriptlets errors
in the output.
This commit adds a new "--scriptletcheck" option that tells mini-tps
to check the output of the YUM command and fail the test if any
problematic words are found.
It's hard to tell how effective this approach will be in the real
world -- only thorough testing will tell.
=> Add "--scriptletcheck" option

mtps-pkg-test
Fixes:
mtps-pkg-test: line 158: cmd_output_parts_prefix: unbound variable
=> Make sure cmd_output_parts_prefix var is declared

mini-tps.spec, mtps-pkg-test, mtps-run-tests
"rpm --verify" should ideally report no problems right after installation.
I.e. what was just installed should match what's in the RPM database.
TPS also performs this check and this feature is an attempt to close the gap
between installability and TPS.
See: OSCI-1240
=> Add "--rpmverify" option

mini-tps.spec, profiles/fedora/prepare-system, profiles/fedora/repos/fedora-36.repo, profiles/fedora/repos/fedora-37.repo, profiles/fedora/repos/fedora-38.repo, profiles/fedora/repos/fedora-39.repo, profiles/fedora/repos/fedora-40.repo, profiles/fedora/repos/fedora-41.repo, profiles/fedora/repos/fedora-42.repo, profiles/fedora/repos/fedora-43.repo, profiles/fedora/repos/fedora-44.repo, profiles/fedora/repos/fedora-45.repo, profiles/fedora/repos/fedora-46.repo
Fedora images already come with all the repo files that we need,
and therefore we don't need to modify or replace them.
However, we still need those empty repo files so that we can
list explicitly supported versions:
$ mtps-prepare-system --list
fedora-36
fedora-37
fedora-38
fedora-39
...
=> Add profiles for Fedora

profiles/centos-stream/repos/centos-stream-8.repo
Tested on a container image, `mtps-prepare-system -p centos-stream-8` passes.
Related to:
https://pagure.io/fedora-ci/general/issue/439
https://github.com/fedora-ci/installability-pipeline/pull/24
=> Add CentOS Stream 8 profile

profiles/centos-stream/prepare-system, profiles/fedora/prepare-system, profiles/rhel/prepare-system
The scripts use `which` and `ps`, but do not make sure they are available. In e.g. official Fedora base container images, they are not, so the test pipeline fails when run in a container.
=> Install which and procps-ng in prepare-system (all profiles)

mtps-pkg-test, mtps-run-tests
https://pagure.io/fedora-ci/general/issue/382
https://gitlab.com/testing-farm/oculus/-/issues/18
Ideally, the prepare phase of the downgrade test would do the same, i.e.
first remove package, then try to install the old one and if that fails, skip the test, otherwise update to the new package.
But that'd be 3 operations (remove, install, update) more than what we do now for every package just for a very rare use-case (old package can't be installed).
Now the prep-downgrade does nothing because the previous (update) test leaves the new package installed.
Also,  have separate exit code for skipped tests so that we can distinguish them in the viewer.
=> Skip update if old package can't be installed

mtps-pkg-test, mtps-run-tests
https://issues.redhat.com/browse/OSCI-6219
=> Treat scriptlet check problems as warnings, not errors

mini-tps.spec, mtps-get-task
We [check it before running tests](https://github.com/fedora-ci/mini-tps/blob/main/mtps-run-tests#L174) but better fail sooner.
There's not much we can do when this problem happens.
We would need to disable the correct module but that might (e.g. in python27 module case) break other packages dependencies.
So just warn the user.
=> Repoquery the test repo in prepare phase

mtps-get-task, profiles/centos-stream/prepare-system, profiles/fedora/prepare-system, profiles/rhel/prepare-system
https://github.com/fedora-ci/mini-tps/pull/45 changed two of the three places we try and do a repoquery operation from calling `"$YUMDNFCMD" repoquery` to just calling `repoquery`, but it missed one. This fixes the remaining one. Also, this attempts to ensure the plain `repoquery` command will always be available. It's not safe to assume this, because it's part of dnf-utils (on Fedora) and yum-utils (on EL), it's not part of core dnf/yum, and nothing much else requires it. It does seem to be missing in the environment in which tests on Fedora package pull requests run, for instance, which caused the test to fail on all pull requests until the build with #45 was temporarily removed.
=> consistently call plain `repoquery`, ensure it is available (#47)

.packit.yaml, profiles/rhel/prepare-system
yum-config-manager is part of yum-utils
=> Install yum-utils before running yum-config-manager

mini-tps.spec, mtps-run-tests
There have been quite a lot of AVCs in the recent Fedora installability pipeline jobs.
91d6d70d is the only SELinux-related change that comes to my mind.
=> Revert "setenforce fails when running in a container"

mini-tps.spec, mtps-run-tests, profiles/fedora/prepare-system
https://github.com/fedora-ci/mini-tps/issues/57#issuecomment-2134998129
Will be removed with a proper fix for the #57
=> Ugly hack for missing config-manager

mtps-pkg-test, mtps-run-tests, mtps-setup, profiles/fedora/prepare-system
https://github.com/fedora-ci/mini-tps/issues/57
=> If dnf5 and dnf-3 are installed, use dnf5

mini-tps.spec, mtps-pkg-test
This seems to be a bug in systemd. See the comment in the code.
=> Ignore (bogus?) warnings about removed systemd unit files being changed on disk and needing to be reloaded

mtps-pkg-test
RHEL 7 has yum v3.4.3. As far as I understood, a downgrade on that version is failing to successfully resolve dependencies available in multiple repos by itself, which results in an error, e.g:
```
Error: Package: freeradius-utils-3.0.13-15.el7.x86_64 (rhel-opt)
Requires: freeradius = 3.0.13-15.el7
Installed: freeradius-3.0.13-15.el7_9.1.x86_64 (@brew-62705510)
freeradius = 3.0.13-15.el7_9.1
Available: freeradius-3.0.13-15.el7.x86_64 (rhel)
freeradius = 3.0.13-15.el7
```
This MR workarounds the issue by adding list of all installed content from the tested task repo to the downgrade command.
=> Workaround for yum v3.4.3 downgrade test

profiles/centos-stream/repos/centos-stream-10.repo
Based on both centos-stream-8 and centos-stream-9, made sure that the urls are up.
=> Add profile for CentOS Stream 10

profiles/rhel/prepare-system
We install the internal CA cert in installability pipeline.
The rpm modifies ldap.conf and openldap installability test then fails.
=> Don't install redhat-internal-cert-install rpm

viewer/generate-result-json
Due to a bug in dnf invalid UTF-8, make sure the viewer does not choke on them.
See:
https://github.com/rpm-software-management/dnf5/issues/1865
for details.
Example of the failure from
https://artifacts.dev.testing-farm.io/c7a1bbdd-1c91-44a9-87ba-f2b9f6fe7dc3/:
```
18:24:51                 out: Running transaction
18:24:51                 out: [1/2] Prepare transaction               100% |  62.0   B/s |   1.0   B |  00m00s
18:24:51                 out: [2/2] Removing spamassassin-debugsource 100% | 147.0   B/s |   9.0   B |  00m00s
18:24:51                 out: Complete!
18:24:51                 out: remove result: fail (status code: 1)
18:24:51                 out: Traceback (most recent call last):
18:24:51                 out:   File …
```
=> viewer: ignore UTF-8 errors

.pre-commit-config.yaml, README.md, mini-tps.spec, mtps-get-builds, mtps-get-module, mtps-get-task, mtps-tag
https://issues.redhat.com/browse/OSCI-7904
=> Konflux imported: Get RPMs from build instead of from a (sub)task(s)

mtps-get-module
even the [API doc](https://brewweb.engineering.redhat.com/brew/api) doesn't mention it
Fixes: https://issues.redhat.com/browse/OSCI-7928
=> getLatestBuilds tag can be a name (string) as well

mtps-get-task
Currently, we check the task to see if the build is a draft. This does not work for import tasks, as those tasks do not necessarily contain this information (and certainly don't for Konflux). Instead, once we have determined that the task is an import, consult the build to determine whether it is a draft or not and then proceed accordingly.
Resolves: OSCI-8507
=> Determine if an imported build is a draft
